# Generated by Django 2.2.5 on 2019-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenInsuredDtls',
            fields=[
                ('insured_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('insured_name', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_dob', models.DateField(blank=True, null=True)),
                ('insured_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_profission', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_addr_code', models.IntegerField(blank=True, null=True)),
                ('insured_phone', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
