# Generated by Django 2.2.5 on 2019-10-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenProductMaster',
            fields=[
                ('prod_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('prod_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('prod_start_date', models.DateField(blank=True, null=True)),
                ('prod_end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
