# Generated by Django 2.2.5 on 2019-10-24 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0002_xxgenagenmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenProductRiskMaster',
            fields=[
                ('risk_code', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('risk_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('risk_premium_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_start_date', models.DateField(blank=True, null=True)),
                ('risk_end_date', models.DateField(blank=True, null=True)),
                ('prem_calc_method', models.CharField(blank=True, max_length=200, null=True)),
                ('fixed_prem', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fixed_si', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenProductMaster')),
            ],
        ),
        migrations.DeleteModel(
            name='XxgenAgenMaster',
        ),
    ]
