# Generated by Django 2.2.5 on 2019-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0003_auto_20191024_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenAgenMaster',
            fields=[
                ('agen_id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(blank=True, max_length=200, null=True)),
                ('agent_dob', models.DateField(blank=True, null=True)),
                ('agent_age', models.IntegerField(blank=True, null=True)),
                ('agent_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('agent_join_date', models.DateField(auto_now_add=True, null=True)),
                ('agent_start_date', models.DateField(blank=True, null=True)),
                ('agent_end_date', models.DateField(blank=True, null=True)),
                ('agent_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('last_update_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
