# Generated by Django 2.2.5 on 2019-10-28 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0005_xxgen_agent_prod_comm_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenVehicleMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfg_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('model_id', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200, null=True)),
                ('engine_cubic_capacity', models.CharField(blank=True, max_length=200, null=True)),
                ('insured_declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('last_update_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'unique_together': {('mfg_company_name', 'model_id', 'model_name')},
            },
        ),
    ]
