# Generated by Django 2.2.5 on 2019-10-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0006_xxgenvehiclemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenVehicleDepriciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_age_from', models.IntegerField(blank=True, null=True)),
                ('vehicle_age_to', models.IntegerField(blank=True, null=True)),
                ('dep_percent_on_idv', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
