# Generated by Django 2.2.5 on 2019-10-29 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0007_xxgenvehicledepriciation'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenNcbMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_years_from', models.BigIntegerField(blank=True, null=True)),
                ('no_years_to', models.BigIntegerField(blank=True, null=True)),
                ('discount_on_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('prod_code', models.ForeignKey(blank=True, db_column='prod_code', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Masters.XxgenProductMaster')),
            ],
        ),
    ]
