# Generated by Django 2.2.5 on 2019-10-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0008_xxgenncbmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenClaimStatusMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clm_status_code', models.CharField(max_length=200, unique=True)),
                ('clm_status_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
