# Generated by Django 2.2.5 on 2019-10-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Masters', '0009_xxgenclaimstatusmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='XxgenClaimsSurveyorMaster',
            fields=[
                ('surveyor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surveyor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_qualificaition', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_brach_code', models.CharField(blank=True, max_length=200, null=True)),
                ('surveyor_city', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_update_date', models.DateField(blank=True, null=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
